# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chassis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Chassis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rChassis.proto\"1\n\x0b\x43hassisData\x12\x10\n\x08velocity\x18\x01 \x01(\x01\x12\x10\n\x08rotation\x18\x02 \x01(\x01\"\\\n\x0f\x43hassisFeedback\x12\x11\n\tleftPower\x18\x01 \x01(\x05\x12\x12\n\nrightPower\x18\x02 \x01(\x05\x12\x10\n\x08velocity\x18\x03 \x01(\x01\x12\x10\n\x08rotation\x18\x04 \x01(\x01\x32=\n\x0e\x43hassisService\x12+\n\x05\x44rive\x12\x0c.ChassisData\x1a\x10.ChassisFeedback(\x01\x30\x01\x62\x06proto3')
)




_CHASSISDATA = _descriptor.Descriptor(
  name='ChassisData',
  full_name='ChassisData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='velocity', full_name='ChassisData.velocity', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='ChassisData.rotation', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=66,
)


_CHASSISFEEDBACK = _descriptor.Descriptor(
  name='ChassisFeedback',
  full_name='ChassisFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leftPower', full_name='ChassisFeedback.leftPower', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightPower', full_name='ChassisFeedback.rightPower', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='ChassisFeedback.velocity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='ChassisFeedback.rotation', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['ChassisData'] = _CHASSISDATA
DESCRIPTOR.message_types_by_name['ChassisFeedback'] = _CHASSISFEEDBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChassisData = _reflection.GeneratedProtocolMessageType('ChassisData', (_message.Message,), {
  'DESCRIPTOR' : _CHASSISDATA,
  '__module__' : 'Chassis_pb2'
  # @@protoc_insertion_point(class_scope:ChassisData)
  })
_sym_db.RegisterMessage(ChassisData)

ChassisFeedback = _reflection.GeneratedProtocolMessageType('ChassisFeedback', (_message.Message,), {
  'DESCRIPTOR' : _CHASSISFEEDBACK,
  '__module__' : 'Chassis_pb2'
  # @@protoc_insertion_point(class_scope:ChassisFeedback)
  })
_sym_db.RegisterMessage(ChassisFeedback)



_CHASSISSERVICE = _descriptor.ServiceDescriptor(
  name='ChassisService',
  full_name='ChassisService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=162,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='Drive',
    full_name='ChassisService.Drive',
    index=0,
    containing_service=None,
    input_type=_CHASSISDATA,
    output_type=_CHASSISFEEDBACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHASSISSERVICE)

DESCRIPTOR.services_by_name['ChassisService'] = _CHASSISSERVICE

# @@protoc_insertion_point(module_scope)
