// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Chassis.proto
#ifndef GRPC_Chassis_2eproto__INCLUDED
#define GRPC_Chassis_2eproto__INCLUDED

#include "Chassis.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class ChassisService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Drive(::grpc::ClientContext* context, const ::ChassisData& request, ::ChassisFeedback* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChassisFeedback>> AsyncDrive(::grpc::ClientContext* context, const ::ChassisData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChassisFeedback>>(AsyncDriveRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ChassisFeedback>* AsyncDriveRaw(::grpc::ClientContext* context, const ::ChassisData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Drive(::grpc::ClientContext* context, const ::ChassisData& request, ::ChassisFeedback* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChassisFeedback>> AsyncDrive(::grpc::ClientContext* context, const ::ChassisData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChassisFeedback>>(AsyncDriveRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::ChassisFeedback>* AsyncDriveRaw(::grpc::ClientContext* context, const ::ChassisData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_Drive_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Drive(::grpc::ServerContext* context, const ::ChassisData* request, ::ChassisFeedback* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Drive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Drive() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Drive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Drive(::grpc::ServerContext* context, const ::ChassisData* request, ::ChassisFeedback* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDrive(::grpc::ServerContext* context, ::ChassisData* request, ::grpc::ServerAsyncResponseWriter< ::ChassisFeedback>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Drive<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Drive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Drive() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Drive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Drive(::grpc::ServerContext* context, const ::ChassisData* request, ::ChassisFeedback* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Drive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Drive() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::ChassisData, ::ChassisFeedback>(std::bind(&WithStreamedUnaryMethod_Drive<BaseClass>::StreamedDrive, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Drive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Drive(::grpc::ServerContext* context, const ::ChassisData* request, ::ChassisFeedback* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDrive(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ChassisData,::ChassisFeedback>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Drive<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Drive<Service > StreamedService;
};


#endif  // GRPC_Chassis_2eproto__INCLUDED
